### PR TITLE
Add License Autoloading

### PR DESCRIPTION
**Pull request by ghost**
These changes make it possible to configure Enterprise License Autoloading with a license file:
* https://www.vaultproject.io/docs/enterprise/license/autoloading
* https://learn.hashicorp.com/tutorials/nomad/hashicorp-enterprise-license?in=vault/enterprise

The change reference the path to the license file in the Vault main configuration:
https://www.vaultproject.io/docs/configuration#license_path

This change does not configure license autoloading via environment variables.

Todo:

- [x] Amend README

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
Thanks for your contribution! Adding a newline at end-of-file helps getting passed the linter.

**Comment by bbaassssiiee** [comment]
yamllint passes, but ansible-lint reports an issue: don't compare to empty string.

**Comment by ghost** [comment]
> yamllint passes, but ansible-lint reports an issue: don't compare to empty string.

Yes, others are experiencing the same behavior here: https://github.com/ansible-community/ansible-lint/issues/457

I decided to go with the suggested workaround for now (check length of string), hope that's fine for you.

Otherwise, we can implement another feature flag just for the upload.

**Review by bbaassssiiee — APPROVED** [review]
LFTM

**Pull request merged**
